### ISSUE TITLE
[master] crash after clearing build plate and loading new model

### ISSUE THREAD

**Issue by smartavionics** [fieldOfView/Cura-MeshTools#10]
![Screenshot_2020-03-22_18-40-43](https://user-images.githubusercontent.com/585618/77257590-308cf280-6c6d-11ea-9e1d-83a8ed7df5e9.png)

From the log...
```
2020-03-22 18:39:36,321 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2020-03-22 18:39:36,324 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2020-03-22 18:39:36,324 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 1028, in event
2020-03-22 18:39:36,324 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     return super().event(event)
2020-03-22 18:39:36,325 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Qt/QtApplication.py", line 460, in event
2020-03-22 18:39:36,325 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     event._function_event.call()
2020-03-22 18:39:36,325 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Event.py", line 218, in call
2020-03-22 18:39:36,325 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._function(*self._args, **self._kwargs)
2020-03-22 18:39:36,326 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 332, in __performEmit
2020-03-22 18:39:36,326 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2020-03-22 18:39:36,326 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/cura/CuraApplication.py", line 1808, in _readMeshFinished
2020-03-22 18:39:36,326 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     operation.push()
2020-03-22 18:39:36,327 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Operations/Operation.py", line 59, in push
2020-03-22 18:39:36,327 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     Application.getInstance().getOperationStack().push(self)
2020-03-22 18:39:36,327 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Operations/OperationStack.py", line 62, in push
2020-03-22 18:39:36,327 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     operation.redo()
2020-03-22 18:39:36,327 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Operations/AddSceneNodeOperation.py", line 46, in redo
2020-03-22 18:39:36,328 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._node.setParent(self._parent)
2020-03-22 18:39:36,328 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Scene/SceneNode.py", line 328, in setParent
2020-03-22 18:39:36,328 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     scene_node.addChild(self)
2020-03-22 18:39:36,328 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Scene/SceneNode.py", line 441, in addChild
2020-03-22 18:39:36,329 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     scene_node._transformChanged()
2020-03-22 18:39:36,329 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Scene/SceneNode.py", line 793, in _transformChanged
2020-03-22 18:39:36,329 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.transformationChanged.emit(self)
2020-03-22 18:39:36,329 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 219, in emit
2020-03-22 18:39:36,330 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2020-03-22 18:39:36,330 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 336, in __performEmit
2020-03-22 18:39:36,330 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     signal.emit(*args, **kwargs)
2020-03-22 18:39:36,330 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 219, in emit
2020-03-22 18:39:36,331 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2020-03-22 18:39:36,331 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 336, in __performEmit
2020-03-22 18:39:36,331 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     signal.emit(*args, **kwargs)
2020-03-22 18:39:36,331 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 219, in emit
2020-03-22 18:39:36,332 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
2020-03-22 18:39:36,332 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/opt/cura/lib/python3/dist-packages/UM/Signal.py", line 332, in __performEmit
2020-03-22 18:39:36,332 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
2020-03-22 18:39:36,333 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/home/markb/.local/share/cura/master/plugins/Cura-MeshTools/MeshTools.py", line 109, in _onSceneChanged
2020-03-22 18:39:36,333 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     # but we want to check the mesh only once
2020-03-22 18:39:36,334 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: argument of type 'NoneType' is not iterable

```

**Comment by fieldOfView** [comment]
That's weird... it says it is crashing on a comment.

**Comment by fieldOfView** [comment]
Could you check if this is fixed with the above commit?

**Comment by smartavionics** [comment]
Oops!
```
2020-03-22 19:27:26,771 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]: Exception: Import error loading module Cura-MeshTools
2020-03-22 19:27:26,775 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]: Traceback (most recent call last):
2020-03-22 19:27:26,776 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/opt/cura/lib/python3/dist-packages/UM/PluginRegistry.py", line 614, in _findPlugin
2020-03-22 19:27:26,777 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     module = imp.load_module(plugin_id, file, path, desc) #type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2020-03-22 19:27:26,778 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/opt/cura/lib/python3.5/imp.py", line 245, in load_module
2020-03-22 19:27:26,778 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     return load_package(name, filename)
2020-03-22 19:27:26,779 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/opt/cura/lib/python3.5/imp.py", line 217, in load_package
2020-03-22 19:27:26,779 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     return _load(spec)
2020-03-22 19:27:26,780 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "<frozen importlib._bootstrap>", line 693, in _load
2020-03-22 19:27:26,780 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2020-03-22 19:27:26,781 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "<frozen importlib._bootstrap_external>", line 697, in exec_module
2020-03-22 19:27:26,781 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2020-03-22 19:27:26,782 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/home/markb/.local/share/cura/master/plugins/Cura-MeshTools/__init__.py", line 4, in <module>
2020-03-22 19:27:26,782 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     from . import MeshTools
2020-03-22 19:27:26,783 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/home/markb/.local/share/cura/master/plugins/Cura-MeshTools/MeshTools.py", line 39, in <module>
2020-03-22 19:27:26,783 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     class MeshTools(Extension, QObject,):
2020-03-22 19:27:26,784 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:   File "/home/markb/.local/share/cura/master/plugins/Cura-MeshTools/MeshTools.py", line 162, in MeshTools
2020-03-22 19:27:26,784 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]:     def _getAllSelectedNodes(self) -> List[SceneNode]:
2020-03-22 19:27:26,785 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [616]: NameError: name 'List' is not defined
2020-03-22 19:27:26,785 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [686]: Could not find plugin Cura-MeshTools

```

**Comment by fieldOfView** [comment]
Sometimes I forget to test things.

**Comment by smartavionics** [comment]
> Sometimes I forget to test things.

You sound like an ideal candidate to work for UM!

Anyway, I can't reproduce the crash with the current master. Thanks.

**Comment by fieldOfView** [comment]
> You sound like an ideal candidate to work for UM!

Been there, done that ;-)
