### ISSUE TITLE
Cura wont enable mashtools

### ISSUE THREAD

**Issue by yagarea** [fieldOfView/Cura-MeshTools#18]
Hi, I installed cura using yay on arch linux. Cura it self works fine. I installed meshtools throw build in market place.  
When I try using meshtools cura acts like their are not installed. When I open market place, cura is installed but unchecked:

![image](https://user-images.githubusercontent.com/14349169/100647375-b7878400-333f-11eb-8fdd-dce03877425b.png)

When I check it, cura says it needs to be restarted to take effect. When I restart cura, box is unchecked again and meshtools act like not installed. 

What should I do to be able to use meshtools ?

Cura version:   
cura version: 4.7.1

**Comment by fieldOfView** [comment]
I can't be 100% sure, but I am guessing whoever created the distribution of Cura you use (ie: not Ultimaker) did not include all dependencies. The logs should tell. If you use the AppImage provided by Ultimaker, the plugin will probably work fine.

**Comment by yagarea** [comment]
```
2020-11-30 19:20:21,795 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: Exception: Import error loading module MeshTools
2020-11-30 19:20:21,795 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: Traceback (most recent call last):
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/site-packages/UM/PluginRegistry.py", line 606, in _findPlugin
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     module = imp.load_module(plugin_id, file, path, desc) #type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/imp.py", line 244, in load_module
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     return load_package(name, filename)
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/imp.py", line 216, in load_package
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     return _load(spec)
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 702, in _load
2020-11-30 19:20:21,796 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/home/john/.local/share/cura/4.7/plugins/MeshTools/MeshTools/__init__.py", line 4, in <module>
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     from . import MeshTools
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/home/john/.local/share/cura/4.7/plugins/MeshTools/MeshTools/MeshTools.py", line 39, in <module>
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     import trimesh
2020-11-30 19:20:21,797 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: ModuleNotFoundError: No module named 'trimesh'
2020-11-30 19:20:21,797 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [678]: Could not find plugin MeshTools
2020-11-30 19:20:21,798 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: Exception: Import error loading module MeshTools
2020-11-30 19:20:21,798 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: Traceback (most recent call last):
2020-11-30 19:20:21,798 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/site-packages/UM/PluginRegistry.py", line 606, in _findPlugin
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     module = imp.load_module(plugin_id, file, path, desc) #type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/imp.py", line 244, in load_module
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     return load_package(name, filename)
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/usr/lib/python3.8/imp.py", line 216, in load_package
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     return _load(spec)
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 702, in _load
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-11-30 19:20:21,799 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-11-30 19:20:21,800 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/home/john/.local/share/cura/4.7/plugins/MeshTools/MeshTools/__init__.py", line 4, in <module>
2020-11-30 19:20:21,800 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     from . import MeshTools
2020-11-30 19:20:21,800 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:   File "/home/john/.local/share/cura/4.7/plugins/MeshTools/MeshTools/MeshTools.py", line 39, in <module>
2020-11-30 19:20:21,800 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]:     import trimesh
2020-11-30 19:20:21,800 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [608]: ModuleNotFoundError: No module named 'trimesh'
```

I installed `trimesh` module manually using yay. Then this error accured:
```
Traceback (most recent call last):
  File "/home/john/.local/share/cura/4.7/plugins/MeshTools/MeshTools/MeshTools.py", line 327, in splitMeshes
    self._replaceSceneNode(node, tri_node.split(only_watertight=False))
  File "/usr/lib/python3.8/site-packages/trimesh/constants.py", line 134, in timed
    result = method(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/trimesh/base.py", line 1291, in split
    return graph.split(self, **kwargs)
  File "/usr/lib/python3.8/site-packages/trimesh/graph.py", line 345, in split
    meshes = mesh.submesh(
  File "/usr/lib/python3.8/site-packages/trimesh/base.py", line 2503, in submesh
    return util.submesh(mesh=self,
  File "/usr/lib/python3.8/site-packages/trimesh/util.py", line 1652, in submesh
    watertight = np.array([i.fill_holes() and len(i.faces) >= 4
  File "/usr/lib/python3.8/site-packages/trimesh/util.py", line 1652, in <listcomp>
    watertight = np.array([i.fill_holes() and len(i.faces) >= 4
  File "/usr/lib/python3.8/site-packages/trimesh/base.py", line 1788, in fill_holes
    return repair.fill_holes(self)
  File "/usr/lib/python3.8/site-packages/trimesh/repair.py", line 257, in fill_holes
    g = nx.from_edgelist(
  File "/usr/lib/python3.8/site-packages/trimesh/exceptions.py", line 28, in __getattribute__
    raise super(ExceptionModule, self).__getattribute__('exc')
  File "/usr/lib/python3.8/site-packages/trimesh/repair.py", line 19, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'

```

 So I installed `networkx` as well and now it works. Thank you for support

**Comment by fieldOfView** [comment]
You are welcome. If you want to do me a favor, raise an issue with the package maintainer so trimesh and its dependencies get added to the package you use. It is not just Mesh Tools that does not work because of this by the way.

**Comment by yagarea** [comment]
Bug reported: https://bugs.archlinux.org/task/68802
