### ISSUE TITLE
Split crashes Cura

### ISSUE THREAD

**Issue by BagelOrb** [fieldOfView/Cura-MeshTools#3]
[UM3_hex_tiles.3mf.removeext.zip](https://github.com/fieldOfView/MeshTools/files/2607225/UM3_hex_tiles.3mf.removeext.zip)

open project > split into parts > CRASH

Perhaps this log entry is relevant:

```
2018-11-22 09:47:22,046 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.03932476043701172 seconds
2018-11-22 09:47:22,054 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_249819784] added.
2018-11-22 09:47:22,055 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [293]: Attempting to kill the engine process
2018-11-22 09:47:22,056 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [299]: Killing engine process
2018-11-22 09:47:22,059 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [302]: Engine process is killed. Received return code -15
2018-11-22 09:47:22,064 - DEBUG - [MainThread] UM.Backend.Backend._createSocket [218]: Previous socket existed. Closing that first.
2018-11-22 09:47:22,070 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.001287698745727539 seconds. 96 input vertices. 96 output vertices.
2018-11-22 09:47:22,082 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.0012810230255126953 seconds
2018-11-22 09:47:22,086 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_106424888] added.
2018-11-22 09:47:22,092 - WARNING - [MainThread] UM.Mesh.MeshData.createConvexHull [410]: Loaded model is low-dimensional, apply QJ to make it full dimensional
2018-11-22 09:47:22,096 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0058383941650390625 seconds. 61 input vertices. 61 output vertices.
2018-11-22 09:47:22,120 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.011483430862426758 seconds
2018-11-22 09:47:22,127 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_199614184] added.
2018-11-22 09:47:22,134 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0013637542724609375 seconds. 72 input vertices. 72 output vertices.
2018-11-22 09:47:22,158 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.008395671844482422 seconds
2018-11-22 09:47:22,164 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_225771736] added.
2018-11-22 09:47:22,171 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0007448196411132812 seconds. 36 input vertices. 36 output vertices.
2018-11-22 09:47:22,204 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.014657020568847656 seconds
2018-11-22 09:47:22,212 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_235614312] added.
2018-11-22 09:47:22,220 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0008361339569091797 seconds. 45 input vertices. 45 output vertices.
2018-11-22 09:47:22,250 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.012780427932739258 seconds
2018-11-22 09:47:22,258 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_252255368] added.
2018-11-22 09:47:22,264 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0009591579437255859 seconds. 41 input vertices. 41 output vertices.
2018-11-22 09:47:22,293 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.01307535171508789 seconds
2018-11-22 09:47:22,299 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_117085048] added.
2018-11-22 09:47:22,305 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0008358955383300781 seconds. 50 input vertices. 50 output vertices.
2018-11-22 09:47:22,325 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.0071294307708740234 seconds
2018-11-22 09:47:22,329 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_250296936] added.
2018-11-22 09:47:22,333 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0005910396575927734 seconds. 40 input vertices. 40 output vertices.
2018-11-22 09:47:22,343 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.0014081001281738281 seconds
2018-11-22 09:47:22,348 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_281452616] added.
2018-11-22 09:47:22,353 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0003364086151123047 seconds. 14 input vertices. 14 output vertices.
2018-11-22 09:47:22,371 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.008328676223754883 seconds
2018-11-22 09:47:22,376 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_283637800] added.
2018-11-22 09:47:22,381 - DEBUG - [MainThread] UM.Mesh.MeshData.approximateConvexHull [401]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0006966590881347656 seconds. 40 input vertices. 40 output vertices.
2018-11-22 09:47:22,389 - DEBUG - [MainThread] UM.Mesh.MeshData.calculateNormalsFromIndexedVertices [467]: Calculating normals took 0.00014090538024902344 seconds
2018-11-22 09:47:22,393 - DEBUG - [MainThread] UM.Settings.ContainerRegistry.addContainer [371]: Container [per_object_stack_121852552] added.
2018-11-22 09:47:22,399 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
2018-11-22 09:47:22,403 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
2018-11-22 09:47:22,407 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 935, in _normalize_shape
2018-11-22 09:47:22,410 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/stride_tricks.py", line 176, in broadcast_to
2018-11-22 09:47:22,413 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/stride_tricks.py", line 128, in _broadcast_to
2018-11-22 09:47:22,416 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (0,2)
2018-11-22 09:47:22,420 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: 
2018-11-22 09:47:22,423 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: During handling of the above exception, another exception occurred:
2018-11-22 09:47:22,427 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
2018-11-22 09:47:22,431 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Qt/Bindings/ExtensionModel.py", line 51, in subMenuTriggered
2018-11-22 09:47:22,434 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Extension.py", line 38, in activateMenuItem
2018-11-22 09:47:22,439 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/t.kuipers/.local/share/cura/3.6/plugins/MeshTools/MeshTools/MeshTools.py", line 171, in splitMeshes
2018-11-22 09:47:22,443 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     self._replaceSceneNode(node, tri_node.split(only_watertight=False))
2018-11-22 09:47:22,446 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/home/t.kuipers/.local/share/cura/3.6/plugins/MeshTools/MeshTools/MeshTools.py", line 199, in _replaceSceneNode
2018-11-22 09:47:22,448 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:     new_node.setMeshData(mesh_data)
2018-11-22 09:47:22,450 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 341, in setMeshData
2018-11-22 09:47:22,453 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 699, in _resetAABB
2018-11-22 09:47:22,455 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 212, in emit
2018-11-22 09:47:22,457 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Signal.py", line 315, in __performEmit
2018-11-22 09:47:22,460 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 136, in calculateBoundingBoxMesh
2018-11-22 09:47:22,464 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Scene/SceneNode.py", line 640, in getBoundingBox
2018-11-22 09:47:22,468 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/Scene/CuraSceneNode.py", line 116, in _calculateAABB
2018-11-22 09:47:22,472 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Mesh/MeshData.py", line 191, in getExtents
2018-11-22 09:47:22,476 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1200, in pad
2018-11-22 09:47:22,479 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 979, in _validate_lengths
2018-11-22 09:47:22,483 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 938, in _normalize_shape
2018-11-22 09:47:22,487 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: ValueError: Unable to create correctly shaped tuple from ((0, 0), (0, 1))
```

**Comment by Black6spdZ** [comment]
most models I attempt to split also crash Cura 
"3.6.0"

**Comment by fieldOfView** [comment]
@Black6spdZ, please post a link to a model that makes the plugin crash.

**Comment by JoaquinBerrios** [comment]
The model "Halfling_Male_Rogue.stl" from the following collection will cause the crash. Not sure if others will as well. The collection is here: https://www.thingiverse.com/thing:2435041

**Comment by fieldOfView** [comment]
I can no longer reproduce this crash in Cura 4.5. I know I've let this issue linger for quite some time, but could you test? It might have been fixed in Cura.
